version: "3.9"  
services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - app-network
    ports:
      - "3306:3306" # Expose MySQL on port 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: your_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - app-network
    ports:
      - "8083:80" # Expose phpMyAdmin on port 8081
    environment:
      PMA_HOST: mysql # The MySQL host to connect to
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql # Wait for MySQL to be ready before starting phpMyAdmin

# Define networks
networks:
  app-network:
    driver: bridge
